### PR TITLE
Auto Encrypt environment variables on serverless package or deploy

### PR DESCRIPTION
**Pull request by anantab**

### CODE REVIEW

**Comment by ztmdsbt** [comment]
1. how to detect the secrets file has already encrypted or not?
1. I don't think that to put the not encrypted variables in code and code repo is a good idea.

**Comment by anantab** [comment]
1. No it does not check if it is already encrypted. You should put unencrypted value, which will then be encrypted before setting environment variable.
2. I always put configuration values in a config file  and gitignore this file. This values are referenced in serverless.yml as below
```
environment: 
    Var1: ${file(../config/config-${opt:stage}.yml)}
```
allowing setting variables for different stage (dev, test, prod etc)  and not putting either encrypted or non encrypted variables in repo with  code.  The configuration file then can be put in separate repo allowing only access based access level or shared by any other method of your choice.

**Comment by risabhkumar-cc** [comment]
Any updates on this? Or any workaround? Need this ASAP.

**Comment by mpuittinen** [comment]
The whole point of the plugin is to avoid storing the env variables in clear text in the first place. That's why the secrets file is encrypted by default

**Pull request closed without merging**
